language: node_js
node_js:
  - "12"
dist: trusty
sudo: false
cache:
  directories:
    - node_modules

addons:
  chrome: stable
branches:
  only:
    - master

install:
  - npm install -g @angular/cli

script:
  - npm run lint
  - npm run test:headless
  - npm run build
  - xvfb-run npm run e2e
  - ng lint
  - npm run test-headless
  - ng build --prod --aot